### ISSUE TITLE
Question: Does this action support blue/green?

### ISSUE THREAD

**Issue by SpencerKaiser** [IBM/actions-ibmcloud-iks#1]
Currently working on a new service we plan to deploy in a couple of weeks and we're looking for an Action to help us deploy to IKS. My understanding is that we'd essentially copy/paste the code you have in your `.github/workflows` directory and modify as needed, is that accurate?

It doesn't look like you have anything in there specifying blue/green, but I'm also new to Kubernetes, so maybe that's something I'm just not knowledgable of yet. If that's not included, how much work would we need to do to incorporate that?

Finally, is the environment variables section just for use with the deployment/running the container or are those variables also passed to app itself inside the container?

Thanks for the help!

**Comment by stevemar** [comment]
Hey @SpencerKaiser thanks for checking out this action.

You don't need to copy/paste the code any longer, clicking the *Actions* tab, and selecting the *New workflow* button should bring up IKS as a deployment option (see the image below)

<img width="1408" alt="iks-starter-workflow" src="https://user-images.githubusercontent.com/4118756/83300846-bb86ed80-a1c6-11ea-9eb2-1935681b7e39.png">

For the blue/green deployment I can't speak to that with 100% accuracy, I'd recommend reading this: https://www.haproxy.com/blog/rolling-updates-and-blue-green-deployments-with-kubernetes-and-haproxy/#blue-green-deployments -- it seems like you'd want to check in your service and deployment YAML files into your repo and maybe tweak the last few lines of the action.

For the environment variables in the action, those are only for the action itself to get the container running, the application itself has no knowledge of those variables. What you're probably looking for are [ConfigMaps](https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-object) and Secrets, a Kubernetes concept for passing predefined data to your application.

**Comment by SpencerKaiser** [comment]
@stevemar awesome, that's incredibly helpful. We're about 2 weeks away from having Actions available to us, so I may have questions when we get started with this action.

I'll close this for now, but I may follow up on this issue again when/if we have questions in the future if that's ok 🙂

Thanks again for the quick and detailed response!
